name: saged
channels:
  - r
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aioeasywebdav=2.4.0
  - aiohttp=3.6.2
  - appdirs=1.4.3
  - async-timeout=3.0.1
  - attrs=19.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.3
  - bcrypt=3.2.0
  - binutils_impl_linux-64=2.34
  - binutils_linux-64=2.34
  - bioconductor-annotate=1.64.0
  - bioconductor-annotationdbi=1.48.0
  - bioconductor-biobase=2.46.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-genefilter=1.68.0
  - bioconductor-iranges=2.20.0
  - bioconductor-limma=3.42.0
  - bioconductor-s4vectors=0.24.0
  - bioconductor-sva=3.18.0
  - bleach=3.1.5
  - blinker=1.4
  - boto3=1.14.43
  - botocore=1.17.43
  - bravado=10.6.1
  - bravado-core=5.17.0
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.6.20
  - cachetools=4.1.1
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - configargparse=1.2.3
  - coverage=5.2.1
  - coveralls=2.1.2
  - cryptography=2.9.2
  - cudatoolkit=10.1.243
  - curl=7.68.0
  - cycler=0.10.0
  - datrie=0.8.2
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - docopt=0.6.2
  - docutils=0.15.2
  - dropbox=10.1.1
  - entrypoints=0.3
  - expat=2.2.9
  - filechunkio=1.8
  - fontconfig=2.13.1
  - freetype=2.10.2
  - fribidi=1.0.9
  - ftputil=4.0.0
  - future=0.18.2
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - gitdb=4.0.5
  - glib=2.65.0
  - google-api-core=1.22.1
  - google-auth=1.20.1
  - google-cloud-core=1.4.1
  - google-cloud-storage=1.30.0
  - google-crc32c=0.1.0
  - google-resumable-media=0.7.1
  - googleapis-common-protos=1.51.0
  - graphite2=1.3.13
  - graphviz=2.38.0
  - grpcio=1.31.0
  - gsl=2.5
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=2.4.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=1.6.1
  - importlib_metadata=1.6.1
  - ipykernel=5.3.0
  - ipython=7.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.1
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.15.1
  - jpeg=9d
  - jsonref=0.2
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.2.0
  - krb5=1.16.4
  - lcms2=2.11
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcrc32c=1.1.1
  - libcurl=7.68.0
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-devel_linux-64=7.5.0
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libprotobuf=3.12.4
  - libsodium=1.0.17
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=7.5.0
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.9
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - make=4.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.1
  - mistune=0.8.4
  - mizani=0.7.1
  - mkl=2020.1
  - monotonic=1.5
  - more-itertools=8.4.0
  - msgpack-python=1.0.0
  - multidict=4.7.5
  - mypy=0.782
  - mypy_extensions=0.4.3
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.1
  - neptune-client=0.4.117
  - networkx=2.4
  - ninja=1.10.0
  - notebook=6.0.3
  - nspr=4.25
  - nss=3.47
  - numpy=1.18.5
  - oauthlib=3.0.1
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.4
  - palettable=3.3.0
  - pandas=1.0.5
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - pango=1.40.14
  - paramiko=2.7.1
  - parso=0.7.0
  - patsy=0.5.1
  - pcre=8.44
  - pcre2=10.35
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.1.1
  - pixman=0.38.0
  - plotnine=0.7.0
  - pluggy=0.13.1
  - prettytable=0.7.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - protobuf=3.12.4
  - psutil=5.7.0
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.9.0
  - py3nvml=0.2.5
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.6.1
  - pygraphviz=1.5
  - pyjwt=1.7.1
  - pynacl=1.3.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=5.4.3
  - pytest-cov=2.10.1
  - python=3.8.3
  - python-dateutil=2.8.1
  - python-irodsclient=0.8.2
  - python_abi=3.8
  - pytorch=1.4.0
  - pytz=2020.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - qtconsole=4.7.5
  - qtpy=1.9.0
  - r=3.6.0
  - r-assertthat=0.2.1
  - r-base=3.6.1
  - r-bit=1.1_14
  - r-bit64=0.9_7.1
  - r-bitops=1.0_6
  - r-blob=1.1.1
  - r-boot=1.3_20
  - r-class=7.3_15
  - r-cluster=2.0.8
  - r-codetools=0.2_16
  - r-dbi=1.0.0
  - r-digest=0.6.18
  - r-foreign=0.8_71
  - r-kernsmooth=2.23_15
  - r-lattice=0.20_38
  - r-magrittr=1.5
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-memoise=1.1.0
  - r-mgcv=1.8_28
  - r-nlme=3.1_139
  - r-nnet=7.3_12
  - r-pkgconfig=2.0.2
  - r-plogr=0.2.0
  - r-prettyunits=1.0.2
  - r-rcpp=1.0.1
  - r-rcurl=1.95_4.12
  - r-recommended=3.6.0
  - r-rpart=4.1_15
  - r-rsqlite=2.1.2
  - r-spatial=7.3_11
  - r-survival=2.44_1.1
  - r-xml=3.98_1.19
  - r-xtable=1.8_4
  - ratelimiter=1.2.0
  - readline=8.0
  - requests=2.24.0
  - requests-oauthlib=1.2.0
  - rpy2=3.3.2
  - rsa=4.6
  - s3transfer=0.3.3
  - scikit-learn=0.23.1
  - scipy=1.4.1
  - sed=4.7
  - send2trash=1.5.0
  - setuptools=47.3.1
  - simplegeneric=0.8.1
  - simplejson=3.17.2
  - sip=4.19.13
  - six=1.15.0
  - smmap=3.0.4
  - snakemake=5.5.4
  - snakemake-minimal=5.5.4
  - sqlite=3.30.1
  - statsmodels=0.11.1
  - swagger-spec-validator=2.7.3
  - sysroot_linux-64=2.12
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tktable=2.10
  - tornado=6.0.4
  - tqdm=4.46.1
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing-extensions=3.7.4.2
  - typing_extensions=3.7.4.2
  - tzlocal=2.1
  - urllib3=1.25.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xmlrunner=1.7.7
  - xmltodict=0.12.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.4.2
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - configparser==5.0.0
    - docker-pycreds==0.4.0
    - gitpython==3.1.7
    - gql==0.2.0
    - graphql-core==1.1
    - nvidia-ml-py3==7.352.0
    - pathtools==0.1.2
    - promise==2.3
    - pyyaml==5.3.1
    - sentry-sdk==0.16.1
    - shortuuid==1.0.1
    - subprocess32==3.5.4
    - wandb==0.9.3
    - watchdog==0.10.3
